site_name: Luwow Documentation
site_url: https://luwow-project.github.io/Documentation/
repo_name: Luwow-Project
repo_url: https://github.com/Luwow-Project/

theme:
  custom_dir: docs/overrides
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.indexes 
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: luwowdoc-dark
      toggle:
        icon: octicons/sun-24
        name: Switch to Light Mode

    - scheme: luwowdoc-light 
      toggle:
        icon: octicons/moon-24
        name: Switch To Dark Mode
  icon:
    repo: octicons/mark-github-16

extra_css:
  - css/colors.css
  - css/theme.css
  - css/code.css
  - css/api-reference.css
  - css/paragraph.css
  - css/home.css

markdown_extensions:
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials: tutorials/index.md
    - Luwow Project Setup: tutorials/setup.md
    - Require Resolution: tutorials/require.md
    - Native Modules: tutorials/nativeModules.md
  - API Reference:
    - API Reference: api-reference/index.md
    - Engine: 
      - Engine: api-reference/engine/index.md
copyright: |
  &copy; 2026 <a href="https://github.com/Luwow-Project"  target="_blank" rel="noopener">Luwow Project</a>